name: run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-13, ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pynumad
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Test with pytest
      run: |
        pip install --upgrade pytest coverage
        coverage run --source=pynumad --omit="*/tests/*" -m pytest
